### ISSUE TITLE
refactor 2

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-ord#3]
setConstructor -> init
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/tests/contracts/nftCounter.ts#L11

**Comment by xhliu** [comment]
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/src/contracts/onesatNFT.ts#L71

This is not raw hex, just a string
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/src/inscription.ts#L5

**Comment by xhliu** [comment]
move all to before()
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/tests/specs/hashPuzzle.spec.ts#L30-L39

**Comment by xhliu** [comment]
Looks like first output is token change? If yes, let's move it to the last, as sat change.
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/tests/specs/hashPuzzle.spec.ts#L63

Also, add comments throughout to explain, e.g.,

1. what are `nexts`?
2. Why is this a burn?
3. What are outputs when callContract?

**Comment by xhliu** [comment]
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/src/contracts/bsv20V1.ts
Let's put inscription at the beginning everywhere.

**Comment by xhliu** [comment]
Change to any amount other than 1, which is confusing to 1sat.
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/tests/contracts/ftCounter.ts#L29

**Comment by xhliu** [comment]
Rename build1SatStateOutput -> buildStateOutputFT & buildStateOutputNFT. 1Sat is too general here.
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/tests/contracts/ftCounter.ts#L28C31-L28C31

**Comment by xhliu** [comment]
Rename changeAmt -> changeTokenAmt
https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/tests/specs/ftCounter.spec.ts#L47C19-L47C28

**Comment by xhliu** [comment]
Add comments for all files under https://github.com/sCrypt-Inc/scrypt-ord/tree/master/src/contracts, at least for all top-level functions.

**Comment by zhfnjust** [comment]
> Looks like first output is token change? If yes, let's move it to the last, as sat change.
> 
> https://github.com/sCrypt-Inc/scrypt-ord/blob/09dbe2ad0d36f240055e8729027b97c4305b2922/tests/specs/hashPuzzle.spec.ts#L63
> 
> Also, add comments throughout to explain, e.g.,
> 
> 1. what are `nexts`?
> 2. Why is this a burn?
> 3. What are outputs when callContract?

1. update `transfer()` returns , no more nexts, just 

```ts
Promise<{
        /** The method calling tx */
        tx: bsv.Transaction;
        changeInstance: BSV20V1 | null
        receivers: Array<BSV20V1>
    }>
```

2. add a burn method, so don't need to tell why this is a burn.
3. first output is a instance holds change token amt, the secound output is the first receiver,  the third output is the secound receiver. last output is change output.

**Comment by zhfnjust** [comment]
> Looks like first output is token change? If yes, let's move it to the last, as sat change.

we can't move it to the last, bcoz 1stat track in sequence.

**Comment by xhliu** [comment]
hash160 -> pubKey2Addr
https://github.com/sCrypt-Inc/scrypt-ord/blob/0ac28b5b057223d41aa1f3e7651e7234fba95546/src/contracts/ordP2PKH.ts#L36

**Comment by xhliu** [comment]
`const tick = toByteString('DOGE', true)
`
https://github.com/sCrypt-Inc/scrypt-ord/blob/master/tests/specs/hashPuzzle.spec.ts#L12C5-L12C24

**Comment by xhliu** [comment]
```ts
const recipients =                     [
                        {
                            instance: new HashPuzzle(
                                toByteString(tick, true),
                                max,
                                lim,
                                sha256(message2)
                            ),
                            amt: 10n,
                        },
                    ]
const { tx, atInputIndex } = await hashPuzzle.methods.unlock(message1, { transfer: recipients, tokenChangeAddress: tokenChangeAddr} as OrdMethodCallOptions)
```
`OrdMethodCallOptions` extends `MethodCallOptions`.
https://github.com/sCrypt-Inc/scrypt-ord/blob/0ac28b5b057223d41aa1f3e7651e7234fba95546/tests/specs/hashPuzzle.spec.ts#L37-L52

**Comment by xhliu** [comment]
Make
https://github.com/sCrypt-Inc/scrypt-ord/blob/0ac28b5b057223d41aa1f3e7651e7234fba95546/tests/specs/hashPuzzle.spec.ts#L35
similar to
https://github.com/sCrypt-Inc/boilerplate/blob/5670d548bbc0d7502f037bb0ae20862ca58a89f9/tests/counter.test.ts#L11

Call/transfer multiple times in a chain of txs.

**Comment by xhliu** [comment]
https://github.com/sCrypt-Inc/scrypt-ord/blob/62d5ee7a9e7662f7ebb5aa60b359aab402566f25/tests/specs/hashPuzzle.spec.ts#L61-L79

**Comment by xhliu** [comment]
Does it support inscribing NFT to a p2pkh? https://github.com/sCrypt-Inc/scrypt-ord/blob/master/src/contracts/ordP2PKH.ts#L25

**Comment by xhliu** [comment]
Move [this](https://github.com/sCrypt-Inc/scrypt-ord/blob/master/src/contracts/1satApis.ts) out of contracts folder to, say, src/.

**Comment by xhliu** [comment]
ordP2PKH = new OrdP2PKH(address) 
https://github.com/sCrypt-Inc/scrypt-ord/blob/62d5ee7a9e7662f7ebb5aa60b359aab402566f25/tests/specs/ordP2PKH.spec.ts#L18

**Comment by xhliu** [comment]
No need to specially handle p2pkh. Can we remove the whole file?
https://github.com/sCrypt-Inc/scrypt-ord/blob/62d5ee7a9e7662f7ebb5aa60b359aab402566f25/tests/specs/ordP2PKH.spec.ts

E.g., this can be just like any other transfer: `ordP2PKH.methods.unlock`
https://github.com/sCrypt-Inc/scrypt-ord/blob/62d5ee7a9e7662f7ebb5aa60b359aab402566f25/tests/specs/ordP2PKH.spec.ts#L27

**Comment by xhliu** [comment]
Just reuse fromTx() https://docs.scrypt.io/how-to-deploy-and-call-a-contract/call-deployed#interact. Again, make API as close as before.
https://github.com/sCrypt-Inc/scrypt-ord/blob/62d5ee7a9e7662f7ebb5aa60b359aab402566f25/tests/specs/fromTxHashPuzzle.spec.ts#L34

**Comment by xhliu** [comment]
[This](https://github.com/sCrypt-Inc/scrypt-ord/blob/master/tests/specs/send2HashPuzzle.spec.ts) is gonna cover https://github.com/sCrypt-Inc/scrypt-ord/issues/5?

**Comment by xhliu** [comment]
Merge https://github.com/sCrypt-Inc/scrypt-ord/blob/master/tests/specs/skipTokenChange.spec.ts into https://github.com/sCrypt-Inc/scrypt-ord/blob/master/tests/specs/hashPuzzle.spec.ts, since lots of same code.

**Comment by xhliu** [comment]
Let's remove all places where p2pkh is treated differently from a contract. It is just ONE contract.
Like https://github.com/sCrypt-Inc/scrypt-ord/blob/62d5ee7a9e7662f7ebb5aa60b359aab402566f25/src/contracts/onesatNFT.ts#L121

**Comment by zhfnjust** [comment]
> Does it support inscribing NFT to a p2pkh? https://github.com/sCrypt-Inc/scrypt-ord/blob/master/src/contracts/ordP2PKH.ts#L25

yes

**Comment by zhfnjust** [comment]
> Do NOT need tx details to call, such as

yes

**Comment by xhliu** [comment]
Use a CONST variable for this magic number. Same everywhere.

**const P2pkhScriptLen = 50**
https://github.com/sCrypt-Inc/scrypt-ord/blob/182478cbf3c270e60e3a6f7b1be25853e2f1f0f3/src/contracts/ordP2PKH.ts#L54
https://github.com/sCrypt-Inc/scrypt-ord/blob/182478cbf3c270e60e3a6f7b1be25853e2f1f0f3/src/contracts/ordP2PKH.ts#L100

**Comment by xhliu** [comment]
`readonly` and comment saying it's dummy. @zhfnjust 
https://github.com/sCrypt-Inc/scrypt-ord/blob/dba56bce7fa3d0a00657beab2ad14bca502dd2e0/src/contracts/bsv20V1.ts#L36

**Comment by xhliu** [comment]
@zhfnjust close this after all is fixed.

**Comment by zhfnjust** [comment]
> Add comments for all files under https://github.com/sCrypt-Inc/scrypt-ord/tree/master/src/contracts, at least for all top-level functions.

#37
