### ISSUE TITLE
typo: sCrpyt -> sCrypt

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-ord#40]
https://github.com/search?q=repo%3AsCrypt-Inc%2Fscrypt-ord%20sCrpyt&type=code

**Comment by yusufidimaina9989** [comment]
Done. https://github.com/sCrypt-Inc/scrypt-ord/pull/42/commits/35ca35c28f8c88571b3208f82c8717a4fa0277f0
