### ISSUE TITLE
Create contract instance from tx

### ISSUE THREAD

**Issue by msinkec** [sCrypt-Inc/scrypt-ord#6]
Currently fails as script doesn't match template. Would this be doable?

**Comment by xhliu** [comment]
Already in and will be in https://github.com/sCrypt-Inc/scrypt-ord/blob/master/tests/specs/fromTxHashPuzzle.spec.ts? @zhfnjust

**Comment by msinkec** [comment]
https://github.com/sCrypt-Inc/scrypt-ord/blob/0d97e75e8afad6f606e09c5ffd5cfbfff8425ffc/src/contracts/oneSatNFT.ts#L182
